server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    username: expsys
    password: 'Swfu@2025'
    type: com.zaxxer.hikari.HikariDataSource
    #siyu:服务器mysql版本为：8.4.2,服务器47.96.10.165，数据库datasci，用户expsys
    #mysql 高版本 Mysql 驱动时，url 后面必须设置时区 serverTimezone
    url: jdbc:mysql://47.96.10.165:3306/datasci?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis_plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
file:
  dir: your_abs_path




